name: build docs
on:
  workflow_dispatch:
    inputs:
      forceDeploy:
        description: 'Force deploy documentation?'
        required: true
        default: 'no'
  push: {branches: ["main", "docs"]}
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Link Check
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --verbose
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Set cache ID
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
