name: build docs
on:
  workflow_dispatch:
    inputs:
      forceDeploy:
        description: 'Force deploy documentation?'
        required: true
        default: 'no'
  push: {branches: ["main", "docs"]}
permissions:
  contents: write
  issues: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: false
      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: docs/requirements.txt
      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
