name: publish pypi
on:
  workflow_dispatch:
    inputs:
      publishToPyPI:
        description: 'Publish to PyPI?'
        required: true
        default: 'no'
permissions:
  contents: write
  pull-requests: write
jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/cgcnn2/
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Generate changelog
        uses: rhysd/changelog-from-release/action@v3
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: -l 2
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Build package with uv
        run: uv build
      - name: Publish package to PyPI
        if: inputs.publishToPyPI == 'yes'
        uses: pypa/gh-action-pypi-publish@release/v1
